### ISSUE TITLE
What is the secure settings value that is changed by this app?

### ISSUE THREAD

**Issue by nerd190** [tytydraco/Immersive#1]
First... **Thank you!** this app is awesome!
I know I can set secure settings values using a terminal emulator with root, or a bash script that can be run on boot (If placed in /system/etc/init.d). I have looked at the files but I am totally lost when it comes to Kotlin/Java. I was wondering, If you would be kind enough to let me know the secure settings values this app changes?
**why?** I would like to automate hiding/showing the navigation bar, based on a certain time or day.
**AGAIN, THANK YOU SO MUCH!**

**Comment by tytydraco** [comment]
Hi! Thanks so much for the email. The secure setting is the global setting
"policy_control". You can write immersive.full=*, immersive.navigation=*,
or immersive.none=*.

Hope this helps!

**Comment by nerd190** [comment]
**Thank you so much!** helped me out alot!
Just had a look at your repo's... very impressive!
I have followed you to keep up with your work! been meaning to learn Kotlin since it came, looks **alot** nicer to work with than java did.
**Thank you again!** currently writing a bash script with a cronjob!

**Comment by tytydraco** [comment]
Thanks again. Sounds like a cool project :)

**Comment by nerd190** [comment]
Sorry for bothering you *again!*
what value does the "full hide" set?
(so the navigation bar can no longer be swiped to reveal itself)
**Thank you for your time**

**Comment by tytydraco** [comment]
You need to set overscan using "wm overscan". My app sets the bottom
overscan to the height of the navigation bar. I don't know the actual
number off the top of my head. You might have to try some values to get it
to work.

**Comment by nerd190** [comment]
Perfect! thank you so much for kindly giving up some of your time! you saved me **tons!**.
The first script & cron simply sets immersive mode (now with choice to completely hide!) depending on time or day (pretty boring! but for me, it has uses) But... this will also play part in a 'gaming mode' script also, OnePlus phones (and others) have alot of  'system table' values to control their 'gaming mode' features, annoyingly whilst immersive is set with 'gaming mode', it doesnt stop the nav-bar revealing itself when dragged (got me killed a bunch of times!) so I am half way through a 'gaming mode' bash script that can be run before your game, that can set things like rotation (lock to landscape), immersive mode (thanks to you!), set one of the kernel profiles you have made (SmartPack/EX kernel manager allow making profiles) etc etc (a little less boring!). Unlike the script/cronjob, I will actually put the 'gaming mode' script on GitHub for others to use, once its done, I will obviously tag you in the ReadMe's credits for the immersive functions, and add a hyperlink to your app's repo!
(I will close the "issue" now, although it was never a issue anyway!)
Just realised your amazing "tagSH" app could also be used to launch/stop my script! *.mind.blown.*
**Thank you for your time and effort!**
